### ISSUE TITLE
Update to the last language design?

### ISSUE THREAD

**Issue by Brouilles** [arturmiz/vuent#119]
Any update to following the official Microsoft React framework ? See https://developer.microsoft.com/en-us/fluentui#/controls/web

In order to have the same design than WinUI 3. 
Thanks!

**Comment by arturmiz** [comment]
The Vuent implementation has been so far based on design toolkits Microsoft provides that can be found here: https://docs.microsoft.com/pl-pl/windows/uwp/design/downloads/
